/// Flutter icons MyIcons
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
///
///

/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
///
///

/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
///
///

/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
///
///
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
///
///
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
///
///
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
///
///

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';

  static const IconData notification_bell =
      const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData location_marker =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData small_calendar =
      const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData padlock = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData computer_screen =
      const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData calendar__1_ =
      const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData verified =
      const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData cancel = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData grid = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData folder = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData shop = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData notification_bell_outline_interface_symbol =
      const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData inbox_mail_empty_tray =
      const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData smartphone__1_ =
      const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData video_camera =
      const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData cloud_computing =
      const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData to_do_list__1_ =
      const IconData(0xe81c, fontFamily: _kFontFam);
}
